# Generated by Django 5.2.7 on 2025-10-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logged_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
