# Generated by Django 5.2.7 on 2025-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
